[package]
name = "hello_cargo"
version = "0.1.0"
authors = ["Evan Savage <evan@savageinter.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
